---
  version: '3.5'

  secrets:
    tomcat_ssl_crt:
      file: ./certificates/tomcat/tomcat-wildcard-dev.crt
    tomcat_ssl_key:
      file: ./certificates/tomcat/tomcat-wildcard-dev.key
    aquarius_service_password:
      file: ./secrets/aquariusPassword.txt

  services:
    aqcu-lookups-service:
      build: .
      image: aqcu-lookups-service
      ports:
        - "7503:7503"
      secrets:
        - source: tomcat_ssl_crt
          target: /home/spring/tomcat-wildcard-ssl.crt
        - source: tomcat_ssl_key
          target: /home/spring/tomcat-wildcard-ssl.key
      env_file:
        - config.env
        - secrets.env
